//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traveller.ApiResource", typeof(ApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Add This Country To Favorites Successfully.
        /// </summary>
        public static string AddedFavorite {
            get {
                return ResourceManager.GetString("AddedFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Added This Photo Successfully.
        /// </summary>
        public static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Added This Video Successfully.
        /// </summary>
        public static string AddVideo {
            get {
                return ResourceManager.GetString("AddVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now You Can Check Your Email .
        /// </summary>
        public static string CheckEmail {
            get {
                return ResourceManager.GetString("CheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Add This City Successfully.
        /// </summary>
        public static string CityAdded {
            get {
                return ResourceManager.GetString("CityAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Delete This Comment Successfully.
        /// </summary>
        public static string DeleteComment {
            get {
                return ResourceManager.GetString("DeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Delete This Country From Favorites Successfully.
        /// </summary>
        public static string DeleteFavorite {
            get {
                return ResourceManager.GetString("DeleteFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Delete This Photo Successfully.
        /// </summary>
        public static string DeletePhoto {
            get {
                return ResourceManager.GetString("DeletePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Delete Reservation Successfully.
        /// </summary>
        public static string DeleteRE {
            get {
                return ResourceManager.GetString("DeleteRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Delete This Video Successfully.
        /// </summary>
        public static string DeleteVideo {
            get {
                return ResourceManager.GetString("DeleteVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Delete This Visit Successfully.
        /// </summary>
        public static string DeleteVisit {
            get {
                return ResourceManager.GetString("DeleteVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Edit This Photo Successfully.
        /// </summary>
        public static string EditPhoto {
            get {
                return ResourceManager.GetString("EditPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Edit Your Profile Successfully.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Edit Reservation Successfully.
        /// </summary>
        public static string EditRE {
            get {
                return ResourceManager.GetString("EditRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Edit This Video Successfully.
        /// </summary>
        public static string EditVideo {
            get {
                return ResourceManager.GetString("EditVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Edit This Visit Successfully.
        /// </summary>
        public static string EditVisit {
            get {
                return ResourceManager.GetString("EditVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Traveller Code Not Valid !!.
        /// </summary>
        public static string InValidCode {
            get {
                return ResourceManager.GetString("InValidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Is Not Valid Email !.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User Name Is InValid !!.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Like This Place Successfully.
        /// </summary>
        public static string LikePlace {
            get {
                return ResourceManager.GetString("LikePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Added This Place Successfuly.
        /// </summary>
        public static string PlaceAdded {
            get {
                return ResourceManager.GetString("PlaceAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Rate This City Successfully.
        /// </summary>
        public static string RateCity {
            get {
                return ResourceManager.GetString("RateCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Rate This Traveller Successfully.
        /// </summary>
        public static string RateTraveller {
            get {
                return ResourceManager.GetString("RateTraveller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Add Report Successfully.
        /// </summary>
        public static string ReportAdded {
            get {
                return ResourceManager.GetString("ReportAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select A Profile Photo !.
        /// </summary>
        public static string RequiredPhoto {
            get {
                return ResourceManager.GetString("RequiredPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Add This  Reservation Successfully.
        /// </summary>
        public static string ReSuccess {
            get {
                return ResourceManager.GetString("ReSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You UnLike This Place Successfully.
        /// </summary>
        public static string UnLikePlace {
            get {
                return ResourceManager.GetString("UnLikePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You was  Added This Country To Favorites .
        /// </summary>
        public static string UserAddFavorites {
            get {
                return ResourceManager.GetString("UserAddFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User Email Is Used , Try Another One !.
        /// </summary>
        public static string UserEmailUsed {
            get {
                return ResourceManager.GetString("UserEmailUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Name Not Found !!.
        /// </summary>
        public static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User Name Is Used , Try Another One !.
        /// </summary>
        public static string UserNameUsed {
            get {
                return ResourceManager.GetString("UserNameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User Phone Is Used , Try Another One !.
        /// </summary>
        public static string UserPhoneUsed {
            get {
                return ResourceManager.GetString("UserPhoneUsed", resourceCulture);
            }
        }
    }
}
