//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calls_Companies
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Name_en { get; set; }
        public string Code { get; set; }
        public string Help_Number { get; set; }
        public string Link { get; set; }
        public int Country_ID { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
