//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int ID { get; set; }
        public double Price { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int Days_Number { get; set; }
        public int Visitors_Number { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public string Description_en { get; set; }
        public int Country_ID { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
