//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Comments
    {
        public int ID { get; set; }
        public string Comment { get; set; }
        public int Report_ID { get; set; }
        public int User_ID { get; set; }
    
        public virtual City_Reports City_Reports { get; set; }
        public virtual User User { get; set; }
    }
}
