//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_City
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public int City_ID { get; set; }
        public string Hotel { get; set; }
        public string Place { get; set; }
        public string Resturant { get; set; }
    
        public virtual City City { get; set; }
        public virtual User User { get; set; }
    }
}
