//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traveller.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Photos
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public double Lat { get; set; }
        public double Log { get; set; }
        public string Location { get; set; }
        public System.DateTime date { get; set; }
        public int User_ID { get; set; }
        public int Country_ID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual User User { get; set; }
    }
}
